# Control file for continuous integration testing at http://travis-ci.org/

language: cpp
compiler: gcc
sudo: required
dist: bionic
before_install:
  - git submodule update --init --recursive
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc-9 g++-9
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-9
  - sudo apt-get update -qy; sudo apt-get install -qy python-dev python3-dev python3.8-dev
script:
  - sed -i 's/CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${OpenMP_C_FLAGS} -O3 -mcx16 -g/CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${OpenMP_C_FLAGS} -O -mcx16 -g -fsanitize=address"/g' CMakeLists.txt
  - sed -i 's/CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS} -O3 -mcx16 -g/CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS} -O -mcx16 -g -fsanitize=address"/g' CMakeLists.txt
  - cmake -H. -Bbuild && cmake --build build -- -j 4 && echo Testing && ASAN_OPTIONS=detect_leaks=1:symbolize=1 LSAN_OPTIONS=verbosity=0:log_threads=1 bin/odgi test
  - export ASAN_OPTIONS=verify_asan_link_order=0
  - cd lib && ls -l && python3.8 -c 'import odgi; g = odgi.graph()'
